version: '3'

services:
  redis:
    container_name: ${CONTAINER_REDIS_NAME}
    image: redis:alpine
    restart: unless-stopped

  postgresql:
    container_name: ${CONTAINER_DB_NAME}
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    volumes:
      - ${DB_PATH}:/var/lib/postgresql/data:rw

  gitlab-runner:
    container_name: ${CONTAINER_GITLAB_RUNNER_NAME}
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${GL_RUNNER_CONFIG}:/etc/gitlab-runner

  gitlab:
    depends_on:
      - postgresql
      - redis
      - gitlab-runner
    container_name: ${CONTAINER_GITLAB_NAME}
    image: 'gitlab/gitlab-ce:13.3.7-ce.0'
    restart: unless-stopped
    volumes:
      - ${GL_CONFIG}:/etc/gitlab:rw
      - ${GL_LOGS}:/var/log/gitlab:rw
      - ${GL_DATA}:/var/opt/gitlab:rw
    ports:
      # the mapped port must match ssh_port specified below.
      - "${EXTERNAL_SSH_PORT}:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        postgresql['enable'] = false
        gitlab_rails['db_username'] = "${POSTGRESQL_USER}"
        gitlab_rails['db_password'] = "${POSTGRESQL_PASSWORD}"
        gitlab_rails['db_host'] = "postgresql"
        gitlab_rails['db_port'] = "5432"
        gitlab_rails['db_database'] = "${POSTGRESQL_DATABASE}"
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = '6379'
        external_url '${EXTERNAL_URL}'
        registry_external_url '${EXTERNAL_REGISTRY_URL}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${EXTERNAL_SSH_PORT}
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
          }
        registry_nginx['listen_port'] = 80
        registry_nginx['listen_https'] = false
        registry_nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
          }
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL} 

networks:
  default:
    external:
      name: ${NETWORK}
