version: '3.8'

services:
  redis:
    image: redis:${REDIS_TAG:-alpine}
    restart: unless-stopped

  postgresql:
    image: postgres:${POSTGRES_TAG:?}
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-gitlab}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?}
      - POSTGRES_DB=${POSTGRES_DATABASE:-gitlabhq}
    volumes:
      - ${LOCAL_POSTRES_DIR:?}:/var/lib/postgresql/data

  gitlab-runner:
    image: gitlab/gitlab-runner:${GITLAB_RUNNER_TAG:-alpine}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LOCAL_RUNNER_CONF_DIR:?}:/etc/gitlab-runner

  gitlab:
    image: ${GITLAB_IMAGE:?}
    depends_on:
      - postgresql
      - redis
      - gitlab-runner
    restart: unless-stopped
    volumes:
      - ${LOCAL_GITLAB_CONF_DIR:?}:/etc/gitlab
      - ${LOCAL_GITLAB_LOGS_DIR:?}:/var/log/gitlab
      - ${LOCAL_GITLAB_DATA_DIR:?}:/var/opt/gitlab
    ports:
      - "${EXTERNAL_SSH_PORT:-22}:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        postgresql['enable'] = false
        gitlab_rails['db_username'] = "${POSTGRES_USER:-gitlab}"
        gitlab_rails['db_password'] = "${POSTGRES_PASSWORD:?}"
        gitlab_rails['db_host'] = "postgresql"
        gitlab_rails['db_port'] = "5432"
        gitlab_rails['db_database'] = "${POSTGRES_DATABASE:-gitlabhq}"
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = '6379'
        external_url '${EXTERNAL_URL:?}'
        registry_external_url '${EXTERNAL_REGISTRY_URL:?}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${EXTERNAL_SSH_PORT:-22}
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
          }
        registry_nginx['listen_port'] = 80
        registry_nginx['listen_https'] = false
        registry_nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
          }
        gitlab_rails['smtp_enable'] = ${EMAIL_ENABLED:-true}
        gitlab_rails['smtp_address'] = "${SMTP_ADDRESS:?}"
        gitlab_rails['smtp_port'] = ${SMTP_PORT:-587}
        gitlab_rails['smtp_user_name'] = "${SMTP_USER_NAME:?}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD:?}"
        gitlab_rails['smtp_domain'] = "${SMTP_DOMAIN:?}"
        gitlab_rails['smtp_authentication'] = "${SMTP_AUTHENTICATION:-login}"
        gitlab_rails['smtp_enable_starttls_auto'] = ${SMTP_ENABLE_STARTTLS_AUTO:-true}
        gitlab_rails['smtp_tls'] = ${SMTP_TLS:-false}
        gitlab_rails['smtp_ssl'] = ${SMTP_SSL:-false}
        gitlab_rails['smtp_openssl_verify_mode'] = "${SMTP_OPENSSL_VERIFY_MODE:-peer}"
        gitlab_rails['gitlab_email_enabled'] = ${EMAIL_ENABLED:-true}
        gitlab_rails['gitlab_email_display_name'] = "${GITLAB_EMAIL_DISPLAY_NAME:-GitLab}"
        gitlab_rails['gitlab_email_from'] = "${GITLAB_EMAIL_FROM:?}"
        gitlab_rails['gitlab_email_reply_to'] = "${GITLAB_EMAIL_REPLY_TO:?}"
      VIRTUAL_HOST: ${DOMAINS:?}
      LETSENCRYPT_HOST: ${DOMAINS:?}
      #LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:?}
    networks: [default, reverse-proxy]

networks:
  reverse-proxy:
    external: true
    name: ${NETWORK:?}
